# Site settings
title: Filocimientos
author:
  name: Cecilia Ivet Molgado Garfias
  email: cezimg@gmail.com
 description: "Filocimientos conocimientos al alcanze de todos" 
 
theme: jekyll-theme-minimal
